#POST http://localhost:8080/users
#Content-Type: application/json
#
#{
#  "email" : "been@babylog.com",
#  "name" : "염삔"
#}


GET http://localhost:8080/users
Content-Type: application/json

#
#PUT http://localhost:8080/users/3
#Content-Type: application/json
#
#{
#  "name":"유니엄마"
#}